#!/bin/bash

sudo -v
if [ $? -ne 0 ]; then
    echo "Access denied."
    exit 1
fi

sudo python -m http.server 80 &
SERVER_PID=$!

trap "sudo kill $SERVER_PID 2>/dev/null; exit" INT EXIT

xdg-open http://localhost:80

wait $SERVER_PID
